[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd vimenter * NERDTree
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
  let g:NERDTreeDirArrows=0
  let g:NERDTreeMouseMode=0
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 111
  let g:indentLine_color_gui = '#708090'
  let g:indentLine_char = '┆'
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
  let g:SuperTabDefaultCompletionType = 'context'
'''

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost,BufEnter * Neomake
  let g:neomake_javascript_enabled_makers = ['eslint']
  let g:neomake_typescript_enabled_makers = ['tslint']
  let g:neomake_html_twig_enabled_makers = ["htmlhint"]
'''

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
#   let g:ale_sign_column_always = 1
#   let g:ale_lint_on_enter = 1
#   let g:ale_lint_on_save = 1
#   let g:ale_lint_on_text_changed = 'never'
#   let g:ale_linters = {
#     \ 'javascript': ['eslint'],
#     \ 'typescript': ['tslint'],
#     \ 'vue': ['vls'],
#     \ 'python': ['flake8'],
#     \ }
#   let g:ale_fixers = {
#     \ 'python': ['autopep8'],
#     \ 'javascript': [],
#     \ 'typescript': [],
#     \ 'vue': [],
#     \ }
#
#   let g:ale_typescript_prettier_use_local_config = 1
#
#   let g:python3_host_prog = expand('$HOME') . '/.pyenv/shims/python3'
#   let g:ale_python_flake8_executable = g:python3_host_prog
#   let g:ale_python_flake8_options = '-m flake8'
#   let g:ale_python_autopep8_executable = g:python3_host_prog
#   let g:ale_python_autopep8_options = '-m autopep8'
#   let g:ale_fix_on_save = 1
# '''
