# for python
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
[[plugins]]
repo = 'tell-k/vim-autopep8'
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_source = ['vim-pyenv']
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview
  let g:jedi#completions_command = "<C-c>"
  let g:jedi#goto_assignments_command = "<C-g>"
  let g:jedi#goto_definitions_command = "<C-d>"
  let g:jedi#documentation_command = "<C-k>"
  let g:jedi#goto_command = "<leader>d"
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R"
  let g:jedi#popup_select_first = 0
  let g:jedi#popup_on_dot = 0
'''
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
# depends = ['davidhalter/jedi-vim']
on_ft = 'python'
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

