# [[plugins]]
# repo = 'othree/yajs.vim'
#
# [[plugins]]
# repo = 'maxmellon/vim-jsx-pretty'
#
# [[plugins]]
# repo = 'othree/es.next.syntax.vim'
#
# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
#
# [[plugins]]
# repo = 'othree/html5.vim'
