[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

# for python
# [[plugins]]
# repo = 'hynek/vim-python-pep8-indent'
# on_ft = 'python'
[[plugins]]
repo = 'tell-k/vim-autopep8'
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_source = ['vim-pyenv']
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview
'''
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['davidhalter/jedi-vim']
on_ft = 'python'
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
