# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'
# on_ft = ['javascript', 'typescript', 'css', 'scss', 'json', 'markdown']
# hook_add = '''
#   let g:prettier#autoformat = 0
#   let g:prettier#quickfix_enabled = 0
#   autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
# '''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
  autocmd BufRead,BufNewFile *.ts,*.tsx set filetype=typescript
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript']
hook_add = '''
  autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
'''

# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['typescript']
# hook_add = '''
#   let g:nvim_typescript#javascript_support = 1
#   autocmd BufNewFile,BufRead *.ts set filetype=typescript
# '''

# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue']
# hook_add = '''
#   let g:vue_pre_processors = ['typescript', 'scss']
#   autocmd FileType vue syntax sync fromstart
# '''
