# ============================================================
# JSX / TSX タグの自動補完
# ============================================================
[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = ['typescript', 'typescriptreact', 'javascript', 'javascriptreact']
depends = ['nvim-treesitter']
hook_source = '''
  lua << EOF
  require('nvim-ts-autotag').setup()
EOF
'''
