[[plugins]]
repo = 'dense-analysis/ale'
hoo_add = '''
  let g:ale_fix_on_save = 1
  let g:ale_completion_autoimport = 1
  let g:ale_linters = {
    \ 'html': [],
    \ 'css': ['stylelint'],
    \ 'javascript': ['eslint'],
    \ 'typescript': ['eslint', 'tsserver']
    \ 'vue': ['eslint']
    \ }
  let g:ale_linter_aliases = {'vue': 'css'}
'''

# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'
# on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
# hook_add = '''
#   let g:prettier#autoformat = 0
#   let g:prettier#quickfix_enabled = 0
#   autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
# '''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
  autocmd BufRead,BufNewFile *.ts set filetype=typescript
'''

# [[plugins]]
# repo = 'peitalin/vim-jsx-typescript'
# on_ft = ['typescript']
# hook_add = '''
#   autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.tsx
# '''

# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['typescript']
# hook_add = '''
#   let g:nvim_typescript#javascript_support = 1
#   autocmd BufNewFile,BufRead *.ts set filetype=typescript
# '''

# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue']
# hook_add = '''
#   let g:vue_pre_processors = ['typescript', 'scss']
#   autocmd FileType vue syntax sync fromstart
# '''
