eval $(/opt/homebrew/bin/brew shellenv)

export LSCOLORS=gxfxcxdxbxegedabagacad
alias ls='ls -GCF'
alias ll='ls -la'
alias la='ls -CFal'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias sc='screen'
alias ps='ps --sort=start_time'
alias vim=nvim

# 環境変数
export HISTSIZE=100000 # これだけコマンド履歴を残す
export LANG='ja_JP.UTF-8' # 以下 3 つ文字コード
export LC_ALL='ja_JP.UTF-8'
export LC_MESSAGES='ja_JP.UTF-8'

export PATH="$PATH:$HOME/development/flutter/bin"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH" # for Claude Code
export PATH="$HOME/bin:$PATH" # for Cursor CLI

# mise.toml のあるディレクトリではその版を、それ以外では ~/.config/mise/config.toml の版を使う
eval "$(mise activate bash --shims)"


# Added by Antigravity CLI installer
export PATH="$HOME/.local/bin:$PATH"
