export LSCOLORS=gxfxcxdxbxegedabagacad
alias ls='ls -GCF'
alias ll='ls -la'
alias la='ls -CFal'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias sc='screen'
alias ps='ps --sort=start_time'
alias vim=nvim

# 環境変数
export HISTSIZE=100000 # これだけコマンド履歴を残す
export LANG='ja_JP.UTF-8' # 以下 3 つ文字コード
export LC_ALL='ja_JP.UTF-8'
export LC_MESSAGES='ja_JP.UTF-8'

# for neovim
export XDG_CONFIG_HOME=$HOME/.nvim

# for Golang
export GOPATH=$HOME/.go
export GOENV_ROOT=$HOME/.goenv
export PATH=bin:$GOENV_ROOT/bin:$GOPATH/bin:$PATH
eval "$(goenv init -)"

# # for node
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"


# for embulk
export PATH="$HOME/.embulk/bin:$PATH"

# for ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# for php
export PATH="/Users/yuma/.phpenv/bin:$PATH"
eval "$(phpenv init -)"

# for android
export PATH=${PATH}:/Users/yuma/Library/Android/sdk/platform-tools:/Users/yuma/Library/Android/sdk/tools
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=${JAVA_HOME}/bin:$PATH
export PATH=/usr/local/bin:$PATH
