export LSCOLORS=gxfxcxdxbxegedabagacad
alias ls='ls -GCF'
alias ll='ls -la'
alias la='ls -CFal'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias sc='screen'
alias ps='ps --sort=start_time'

# 環境変数
#export PATH=$PATH:/sbin:/usr/sbin # パス
export PAGER='/usr/bin/lv -c' # man とかで使われる
export EDITOR='/usr/bin/vim' # visudo とかで使われる
export HISTSIZE=100000 # これだけコマンド履歴を残す
export LANG='ja_JP.UTF-8' # 以下 3 つ文字コード
export LC_ALL='ja_JP.UTF-8'
export LC_MESSAGES='ja_JP.UTF-8'

# for python
#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"

# for Golang
#export GOROOT=/usr/local/opt/go/libexec
#export GOPATH=$HOME/gocode
#export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# for postgres
#PATH=$PATH:$HOME/bin:/usr/local/pgsql/bin
#export POSTGRES_HOME=/usr/local/pgsql
#export PGDATA=/data/pgdata
#export PGLIB=$POSTGRES_HOME/lib
#export LD_LIBRARY_PATH=$POSTGRES_HOME/lib

# node.js
#export PATH=$HOME/.nodebrew/current/bin:$PATH

# for embulk
export PATH="$HOME/.embulk/bin:$PATH"
